### ISSUE TITLE
[composer] tabster error when switching to tables

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5710] opened 2024-02-19 03:06 UTC
render crash that references `tabster` when switching to table during demo.
approx 6pm ET Feb 18 (check logs @wittjosiah?)

<img width="1270" alt="Screenshot 2024-02-19 at 11 05 30 AM" src="https://github.com/dxos/dxos/assets/3523355/8e1dfc82-b00f-4afb-8ebe-c4778547816e">

**Comment by thure** [comment] 2024-02-19 04:08
Unable to reproduce. Please include repro steps or a screen capture, otherwise I may need to pair with you if the repro is device-specific.

**Comment by richburdon** [comment] 2024-02-19 16:26
https://github.com/dxos/dxos/assets/3523355/e81a7c23-e23f-4909-a0c9-595e599128e8

**Comment by thure** [comment] 2024-02-19 17:54
I don’t have access to AI features, so this repro won’t work for me unfortunately. I also need a local dev repro — if this is only breaking when bundled, the problem is with the bundler.

If you can provide a repro that doesn’t involve AI that repro’s locally, that will unblock me.

**Comment by thure** [comment] 2024-02-23 20:46
Sounds like this resolved on its own, so closing this for now. Please reopen if needed.

**Closed by thure** 2024-02-23 20:46 UTC
Labels: bug
