### ISSUE TITLE
[authoring] top of document is cut off when first loaded

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5742] opened 2024-02-21 16:43 UTC
![Image](https://github.com/dxos/dxos/assets/4529818/6202fb7a-a715-489e-9223-a3e214943fea)

**Comment by thure** [comment] 2024-02-21 20:06
Part of #5695 was moving overflow to `cm-scroller`, an element that CodeMirror expects to have overflow otherwise its positioning APIs like `EditorState.doc.lineAt` won’t work as expected, which we likewise need for the `cursorLineMargin` extension to work.

CM is doing something on mount that it shouldn’t do, but I can’t find what could be causing that behavior. Adding an effect in react for scrolling to the top when `editorRef` changes works, but it’s fighting with whatever else may be scrolling the document.

**Comment by richburdon** [comment] 2024-02-22 15:23
The issue comes from adding `editorHalfViewportOverscrollContent` (i.e., `after:min-bs-[50dvh]`) to the editor content, which confuses CM's height calculations.

**Comment by thure** [comment] 2024-02-22 17:17
De-escalating since this now has a mitigation.

**Comment by thure** [comment] 2024-02-22 17:18
Current task:
- [ ] produce a minimal reproduction in storybook

**Comment by thure** [comment] 2024-02-26 20:16
Resolved by #5776.

**Closed by thure** 2024-02-26 20:16 UTC
Labels: bug
