### ISSUE TITLE
[cli] error when using dx app create

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#3462] opened 2023-06-13 15:40 UTC
when running dx app create I get:

```
scratch dx --version
@dxos/cli/0.1.48-next.806c124 darwin-x64 node-v18.16.0
➜  scratch ls
foos
➜  scratch dx app create foof
(node:49339) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
    TypeError: Cannot read properties of undefined (reading 'configDir')
➜  scratch 
```

**Comment by nferch** [comment] 2023-06-13 15:57
This is a duplicate of https://github.com/dxos/dxos/issues/3247, no?

**Closed** 2023-06-13 19:31 UTC
Labels: bug, dupe, sdk
