### ISSUE TITLE
Desktop and mobile clients fail to sync

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2690] opened 2023-03-08 21:36 UTC
After reloading the mobile client window, desktop client shows the mobile device is green, but writes from the mobile device are not replicating to the desktop device. (desktop device clearly transitioned from gray to green for the mobile device status moments before). After a short time desktop client "stalled 1000ms with 3 feeds" and later "Error: Timeout [3000ms]" and finally connction error.

The mobile device performed deletions of the bottom four items in the list (Foo ... bar. Their order was inconsistent with the desktop version per #2688 )

mobile device just went online:
<img width="1334" alt="Screenshot 2023-03-08 at 4 31 10 PM" src="https://user-images.githubusercontent.com/3398896/223855541-405dc090-99b8-405a-a3b5-31140f4d98d7.png">
reloaded desktop client, mobile device still online (writes have already been performed on mobile)
<img width="1334" alt="Screenshot 2023-03-08 at 4 31 42 PM" src="https://user-images.githubusercontent.com/3398896/223855738-bef38756-1cfd-49ec-8892-0a1a191ce53e.png">
A while later
<img width="1334" alt="Screenshot 2023-03-08 at 4 32 09 PM" src="https://user-images.githubusercontent.com/3398896/223855796-096defed-a2b5-4e3f-b16a-3a78792e87b4.png">

**Comment by zhenyasav** [comment] 2023-03-08 21:46
Toggling the connection on one or both ends will help restore the green status of the other device, but the lists do not proceed to synchronize in any way. The apps are self-consistent (different tabs see the same task list) but not synchronizing over the air.

My mobile device is on the same wifi as my desktop device.

**Comment by dmaretskyi** [comment] 2023-03-21 11:52
Duplicate of [#2697](https://github.com/dxos/dxos/issues/2697)
We've fixed WebRTC connection retry recently, so lets see if the error appears again

**Closed by dmaretskyi** 2023-03-21 11:52 UTC
Labels: bug
