### ISSUE TITLE
Plugin rendering is broken in the editor

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/dxos#5840] opened 2024-03-04 15:47 UTC
![image](https://github.com/dxos/dxos/assets/35851437/f8d01690-75be-4961-91b6-79aadb4f2425)
![image](https://github.com/dxos/dxos/assets/35851437/37cbceb7-c9a4-41a4-9d89-4e7b74cf0d22)
![image](https://github.com/dxos/dxos/assets/35851437/10c3f3ee-c717-4c62-89f4-22e2b0128208)

**Comment by wittjosiah** [comment] 2024-03-04 15:55
Closing as duplicate of #5841

**Closed by wittjosiah** 2024-03-04 15:55 UTC
