### ISSUE TITLE
[composer] scrolling layout on ipad is strange

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#5793] opened 2024-02-27 15:58 UTC
on Ipad, the entire window scrolls (incl. topbar) and there is something a strange white blank stripe towards the bottom of the screen.

![Image](https://github.com/dxos/dxos/assets/3523355/1d27be9e-ead4-4492-97aa-bb0ea01ec6a5)
![Image](https://github.com/dxos/dxos/assets/3523355/11004d25-cda9-4290-aa29-2fd5eb887101)
![Image](https://github.com/dxos/dxos/assets/3523355/1bf2e202-737b-4e05-be32-33f909c251eb)
![Image](https://github.com/dxos/dxos/assets/3523355/065d107a-6c2c-49ed-b56b-6a2fe71a9816)

**Comment by thure** [comment] 2024-02-28 21:50
If this isn’t Safari, I’m not sure if it’s worthwhile to fix.

Based on the description, I am not able to reproduce (after having fixed #5794, which may have inadvertently fixed this).

Marking as blocked for now, please reopen if the PR resolving #5794 gets merged and this can be reproduced in Safari.

**Closed** 2024-05-02 06:32 UTC
Labels: bug, norepro
