### ISSUE TITLE
[navtree] drag & drop improvements

### ISSUE THREAD

**Issue by wittjosiah** [dxos/dxos#5590] opened 2024-02-07 17:47 UTC
Dragging into a folder from above is difficult because the items move, implementing a line placeholder should help resolve this so that content doesn't shift around in the tree as you're dragging.

### Stretch Goal

It's not currently possible to drop into a collapsed folder for technical reasons. Investigate with we can work around these problems now or if this should be split out and deferred to solve later.

One workaround idea would be that holding an item over a folder for X amount of time will cause the folder to open so you can drop in it.

**Comment by thure** [comment] 2024-02-22 02:15
Thinking about the edges of this, I think there isn’t a way we can intervene on dnd-kit’s collision algorithms that would solve this problem.

The root cause is that the tree doesn’t have the flat structure needed to facilitate even the baseline criterion of success for 5590.

I think if we want to solve the baseline problem and open up the possibility of solving the stretch goal, unfortunately we need to flatten `NavTree` to a single `SortableContext`.

I’m updating the estimate for this to reflect what the refactor would cost that facilitates durable solutions to the problems mentioned here. Marking as blocked until priority or order can be reevaluated given the increased cost.

**Comment by thure** [comment] 2024-02-22 18:03
The scope of this should change:
- Refactor `NavTree` to use only one `SortableContext`
  - this involves “flattening the tree”, meaning Graph needs to produce one flat canonical order for the whole tree
  - we should try not to affect the DOM and use `display: contents`
  - while the tree is flat, refactor layout to use CSS grid
- DnD within the tree can then use an interaction design similar to that of the example in `dnd-kit`

**Closed** 2024-08-03 02:31 UTC
Labels: bug
