### ISSUE TITLE
[organization] fold personal space and spaces into just "spaces" with special "personal space" in it

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#6011] opened 2024-03-18 20:00 UTC

**Comment by wittjosiah** [comment] 2024-03-28 11:19
I remember our discussion of this featuring some sort of share lock on _every space_ which would be turned on by default on your personal space.

**Comment by wittjosiah** [comment] 2024-06-18 17:08
Duplicate of #4418

**Closed by wittjosiah** 2024-06-18 17:08 UTC
Labels: feature, clarify
