### ISSUE TITLE
Task list in Kai synced out of order

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2688] opened 2023-03-08 21:27 UTC
After getting a desktop client to be disconnected from the mobile client for a while, writes were performed on both clients during the partition
Before the partition, the lists were both identical:
- safsafsaf
- f
- f
- fsafasf

During the partition, the desktop device added two items
- foooo
- bar

During the partition, Mobile device added:
- Foo
- Barr

when both clients were reloaded, they settled on this state:
![IMG_0520](https://user-images.githubusercontent.com/3398896/223853986-23cf39a7-3854-4315-a6c5-d9681487b24f.PNG)
<img width="1221" alt="Screenshot 2023-03-08 at 4 26 17 PM" src="https://user-images.githubusercontent.com/3398896/223854026-608d6420-ba54-4f23-822a-7f97d3dd8f54.png">

**Comment by dmaretskyi** [comment] 2023-03-21 11:51
Looks like a duplicate of [#2697](https://github.com/dxos/dxos/issues/2697)

**Closed by dmaretskyi** 2023-03-21 11:51 UTC
Labels: bug
