### ISSUE TITLE
composer navigating documents rapidly fails to render the editor sometimes

### ISSUE THREAD

**Issue by zhenyasav** [dxos/dxos#2855] opened 2023-03-28 06:48 UTC

**Comment by mykola-vrmchk** [comment] 2023-03-28 09:33
related https://github.com/dxos/dxos/issues/2826

**Comment by thure** [comment] 2023-03-31 04:31
There is no repro or screen recording so I'm marking this as a duplicate of #2826.

**Closed by thure** 2023-03-31 04:31 UTC
Labels: bug
