### ISSUE TITLE
[authoring] autocomplete for internal links are broken

### ISSUE THREAD

**Issue by jessmartin** [dxos/dxos#6595] opened 2024-05-07 19:13 UTC
- expected behavior is that ctrl-space would open an auto-complete dialog with the list of all internal objects (or at least documents)
- should be triggered by `[[` for discoverability
- people often have ctrl-space mapped to other things (spotlight, raycast, alfred, for example).

see also #5152

**Comment by ZaymonFC** [comment] 2024-07-03 17:49
Blocked on https://github.com/dxos/dxos/issues/5187. We need better search infrastructure first.

**Comment by wittjosiah** [comment] 2024-07-05 18:50
Duplicate of #5152

**Closed by wittjosiah** 2024-07-05 18:50 UTC
Labels: bug
