### ISSUE TITLE
[composer] spurious header formatting before bullet

### ISSUE THREAD

**Issue by seagreen** [dxos/dxos#6543] opened 2024-05-03 16:08 UTC
In Composer's Markdown editor, if you create a first line which is plain text, followed by a second line which is an empty bullet, the first line is displayed as a header. Once you add some text to the bullet the first line goes back to being displayed as normal text.

https://github.com/dxos/dxos/assets/1310143/9ca1232a-4a46-453b-a9a3-d0e3dea6d9f3

(Happing on the `main` branch)

**Comment by zhenyasav** [comment] 2024-05-07 19:38
dupe of #6168

**Closed by zhenyasav** 2024-05-07 19:38 UTC
